apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 632702791370.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newName: 632702791370.dkr.ecr.us-west-2.amazonaws.com/demo-frontend
  newTag: d7334385
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
